version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}

  web:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
    db-data:
